name: aset_and_properti_up_lsm
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dropdown_search: ^5.0.6
  fluttertoast: 8.2.2
  firebase_auth: ^4.17.8
  firebase_core: ^2.27.0
  flutter:
    sdk: flutter
  get: 4.6.6
  intl: ^0.19.0
  cloud_firestore: ^4.15.8
  firebase_storage: ^11.6.9
  image_picker: ^1.0.8

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/image/
  uses-material-design: true
